"""Media storage contracts for local scratch and private Cloudflare R2."""
from __future__ import annotations

import hashlib
import mimetypes
import os
import re
import shutil
from abc import ABC, abstractmethod
from pathlib import Path
from typing import BinaryIO, Optional
from uuid import uuid4

from content_factory_core import MediaRef

_SAFE_NAME = re.compile(r"[^A-Za-z0-9._-]+")


class MediaStorageAdapter(ABC):
    @abstractmethod
    def put_file(self, source: Path, *, provenance: str, mime_type: Optional[str] = None) -> MediaRef:
        raise NotImplementedError

    @abstractmethod
    def resolve_local(self, media: MediaRef) -> Path:
        raise NotImplementedError


class LocalScratchStorage(MediaStorageAdapter):
    def __init__(self, root: Path):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def _sha256(path: Path) -> str:
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
        return digest.hexdigest()

    @staticmethod
    def _safe_filename(name: str) -> str:
        cleaned = _SAFE_NAME.sub("_", Path(name).name).strip("._")
        return cleaned or "media.bin"

    def put_file(self, source: Path, *, provenance: str, mime_type: Optional[str] = None) -> MediaRef:
        source = Path(source).resolve(strict=True)
        if not source.is_file():
            raise ValueError("source must be a regular file")
        media_id = str(uuid4())
        safe_name = self._safe_filename(source.name)
        target_dir = (self.root / media_id).resolve()
        if self.root not in target_dir.parents:
            raise ValueError("unsafe storage target")
        target_dir.mkdir(parents=True, exist_ok=False)
        target = target_dir / safe_name
        shutil.copy2(source, target)
        digest = self._sha256(target)
        detected = mime_type or mimetypes.guess_type(safe_name)[0] or "application/octet-stream"
        return MediaRef(
            media_id=media_id,
            uri=f"scratch://{media_id}/{safe_name}",
            sha256=digest,
            size_bytes=target.stat().st_size,
            mime_type=detected,
            provenance=provenance,
        )

    def resolve_local(self, media: MediaRef) -> Path:
        prefix = "scratch://"
        if not media.uri.startswith(prefix):
            raise ValueError("media URI does not belong to scratch backend")
        relative = media.uri[len(prefix):]
        candidate = (self.root / relative).resolve()
        if self.root not in candidate.parents or not candidate.is_file():
            raise ValueError("unsafe or missing media URI")
        if self._sha256(candidate) != media.sha256:
            raise ValueError("media integrity check failed")
        return candidate


class R2Storage(MediaStorageAdapter):
    """Private S3-compatible Cloudflare R2 backend.

    Object keys are generated by the factory; caller-controlled paths are never
    accepted. Downloads are materialized into a private local cache and verified
    against the immutable MediaRef SHA-256 before use.
    """

    def __init__(
        self,
        *,
        account_id: str,
        access_key_id: str,
        secret_access_key: str,
        bucket: str,
        cache_root: Path,
        endpoint_url: Optional[str] = None,
        client=None,
    ):
        if not all(str(x or "").strip() for x in (account_id, access_key_id, secret_access_key, bucket)):
            raise ValueError("R2 account, credentials and bucket are required")
        self.account_id = account_id.strip()
        self.bucket = bucket.strip()
        self.cache_root = Path(cache_root).resolve()
        self.cache_root.mkdir(parents=True, exist_ok=True)
        self.endpoint_url = (endpoint_url or f"https://{self.account_id}.r2.cloudflarestorage.com").rstrip("/")
        if client is None:
            try:
                import boto3
            except ImportError as exc:
                raise RuntimeError("boto3 is required for R2Storage") from exc
            client = boto3.client(
                "s3",
                endpoint_url=self.endpoint_url,
                aws_access_key_id=access_key_id,
                aws_secret_access_key=secret_access_key,
                region_name="auto",
            )
        self.client = client

    @classmethod
    def from_env(cls, *, cache_root: Path):
        required = {
            "account_id": os.environ.get("R2_ACCOUNT_ID", ""),
            "access_key_id": os.environ.get("R2_ACCESS_KEY_ID", ""),
            "secret_access_key": os.environ.get("R2_SECRET_ACCESS_KEY", ""),
            "bucket": os.environ.get("R2_BUCKET_NAME", ""),
        }
        missing = [k for k, v in required.items() if not v.strip()]
        if missing:
            raise ValueError("missing R2 configuration: " + ", ".join(missing))
        return cls(
            **required,
            endpoint_url=os.environ.get("R2_ENDPOINT") or None,
            cache_root=cache_root,
        )

    @staticmethod
    def _sha256(path: Path) -> str:
        return LocalScratchStorage._sha256(path)

    @staticmethod
    def _safe_filename(name: str) -> str:
        return LocalScratchStorage._safe_filename(name)

    def put_file(self, source: Path, *, provenance: str, mime_type: Optional[str] = None) -> MediaRef:
        source = Path(source).resolve(strict=True)
        if not source.is_file():
            raise ValueError("source must be a regular file")
        if not provenance.strip():
            raise ValueError("provenance is required")
        media_id = str(uuid4())
        safe_name = self._safe_filename(source.name)
        key = f"media/{media_id}/{safe_name}"
        digest = self._sha256(source)
        detected = mime_type or mimetypes.guess_type(safe_name)[0] or "application/octet-stream"
        self.client.upload_file(
            str(source),
            self.bucket,
            key,
            ExtraArgs={
                "ContentType": detected,
                "Metadata": {"sha256": digest, "media-id": media_id},
            },
        )
        return MediaRef(
            media_id=media_id,
            uri=f"r2://{self.bucket}/{key}",
            sha256=digest,
            size_bytes=source.stat().st_size,
            mime_type=detected,
            provenance=provenance,
        )

    def _object_key(self, media: MediaRef) -> str:
        prefix = f"r2://{self.bucket}/"
        if not media.uri.startswith(prefix):
            raise ValueError("media URI does not belong to configured R2 bucket")
        key = media.uri[len(prefix):]
        expected_prefix = f"media/{media.media_id}/"
        if not key.startswith(expected_prefix) or ".." in key.split("/"):
            raise ValueError("unsafe or foreign R2 media URI")
        return key

    def resolve_local(self, media: MediaRef) -> Path:
        key = self._object_key(media)
        target_dir = (self.cache_root / media.media_id).resolve()
        if self.cache_root not in target_dir.parents:
            raise ValueError("unsafe cache target")
        target_dir.mkdir(parents=True, exist_ok=True)
        target = (target_dir / self._safe_filename(Path(key).name)).resolve()
        if target_dir not in target.parents:
            raise ValueError("unsafe cache path")
        self.client.download_file(self.bucket, key, str(target))
        if target.stat().st_size != media.size_bytes or self._sha256(target) != media.sha256:
            target.unlink(missing_ok=True)
            raise ValueError("R2 media integrity check failed")
        return target
